// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/17/2025, 8:38:39 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/plugins/**/*.{js,ts,mjs}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/composables/**/*.{js,ts,mjs}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/utils/**/*.{js,ts,mjs}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tomboullay/Desktop/Apps/2025/Cours/iotm1/tools/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;